# Generated by Django 5.0.1 on 2024-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/static/profile.jpg', null=True, upload_to=''),
        ),
    ]
