# Generated by Django 5.0.1 on 2024-01-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/profile.jpg', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Aqui va la bio'),
        ),
    ]
