# Generated by Django 5.0.1 on 2024-01-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0012_alter_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
    ]
